version: '3.8'

services:
  dev-service:
    container_name: name
    build:
      context: .
      dockerfile: Development.Dockerfile
      args:
        USERNAME: stephan
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ./:/app